# Generated by Django 4.2.11 on 2024-05-08 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0003_contactform"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newspaper",
            name="image_url",
        ),
    ]
